env:
  PACKAGE_NAME: "example-package"
  AUTH_TOKEN: "package-auth-token"
  WORKDIR: "playwright/ci/buildkite"

steps:
  - label: "Run Playwright Tests"
    parallelism: 3
    command: |
      cd $$WORKDIR
      npm ci
      npx playwright install chromium --with-deps
      echo $$CURRENTS_RECORD_KEY
      npx playwright test --config playwright.config.ts --shard=$$((BUILDKITE_PARALLEL_JOB + 1))/$$BUILDKITE_PARALLEL_JOB_COUNT
    plugins:
      - docker#v5.11.0:
          image: "mcr.microsoft.com/playwright:latest"
          propagate-environment: true

secrets:
  - CURRENTS_RECORD_KEY